menu:
    blog: /
    archives: /archives/
    categories: /categories
    # about: /about
    # 標籤: /tags
    github: https://github.com/javaok1987
    rss: /atom.xml


favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: javaok1987
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-69711228-4

# Copyright Infomation
startyear: 2017
