menu:
    首頁: /
    所有文章: /archives/
    分類: /categories
    # 標籤: /tags
    # GitHub: https://github.com/javaok1987
    訂閱: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: javaok1987
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-69711228-4

# Copyright Infomation
startyear: 2017
